[build-system]
requires = [
    "setuptools",
    "setuptools-git"
]
build-backend = "setuptools.build_meta"

[project]
name = "yandex-music-downloader"
version = "2.0.0"
description = "Загрузчик музыки с сервиса Яндекс.Музыка"
requires-python = ">=3.9"
readme = "README.md"
dependencies = [
    "requests",
    "eyed3",
    "browser-cookie3",
    "rich",
    "rich-argparse"
]

[project.scripts]
yandex-music-downloader = "ymd.cli:main"
